/**
 * This Java source file was generated by the Gradle 'init' task.
 */

package assignment4;

import java.nio.charset.Charset;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;

/**
 * This is the generated Hello World Greeting App.
 */
public class App {
  /**
   * The App starting point.
   *
   * @param args Unused program arguments.
   */
  public static void main(String[] args) {
    try {
      // Get the root directory
      String rootDirectory = System.getProperty("user.dir");

      // It the root directory contains app, remove it and the slash before it
      if (rootDirectory.contains("app")) {
        rootDirectory = rootDirectory.substring(0, rootDirectory.indexOf("app") - 1);
      }

      // Create a path to the file
      Path path = Paths.get(rootDirectory, "app", "src", "main", "java", "assignment4", "data", "solarsystems.data");

      // Create a charset
      Charset cs = Charset.forName("UTF-8");

      // Create a new instance of the FileHandler class
      FileHandler fileHandler = new FileHandler();

      // Create an arrayList to save all the solar systems from the file
      ArrayList<SolarSystem> solarSystemsArrayList = fileHandler.readFile(path, cs);

      // Print a welcome message
      System.out.println("Welcome to the Solar System Manager!");

      // Create a new instance of the Editor class
      Editor editor = new Editor();

      // Start the main menu, and when the user exits, save the solar systems to the arraylist
      solarSystemsArrayList = editor.mainMenu(solarSystemsArrayList);

      // Save the solar systems to a file
      fileHandler.writeFile(path, cs, solarSystemsArrayList);

      // Print a goodbye message
      System.out.println("Goodbye!");

    } catch (Exception e) {
      System.out.println("An error occurred: " + e.getMessage() + "\nPlease try again.");
    }
  }
}
